version: '3'

services:

  kibana46:
    image: kibana:4.6.4
    ports:
      - "5601:5601"
    networks:
      - elk46
    depends_on:
      - elasticsearch2_4_0
      
  elasticsearch2_4_0:
    image: elasticsearch:2.4.0
    ports:
      - "9200:9200"
    networks:
      elk46:
        aliases:
          - elasticsearch

  streamer:
    image: mgurov/kibanato-streamator
    networks:
      - elk46
    depends_on:
      - elasticsearch2_4_0
    command: --elasticURL=http://elasticsearch:9200    

networks:

  elk46: